name: go-counting
version: 0.1.0.2

dependencies:
  - base
  - containers

library:
  exposed-modules: Counting
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - go-counting
      - hspec
      - multiset
